### ISSUE TITLE
Randomly mix multi-channel audio

### ISSUE THREAD

**Issue by hido710** [ModarHalimeh/COSPA#1]
Thanks for this amazing work!

Actually, after finding out that the pre-trained models were not in the directory, I tried to train the models myself.
But, the data mixing stages are a bit confusing for me.

1) I'm not sure where to place the microphone array.
2) How can I simply write the lines that randomly picks the room and the spource location?

Could you please answer this question or share the reference code for mixing the data?

Hope you have a great day, bye!

**Comment by ModarHalimeh** [comment]
Hi Hido,

Thank you for your kind words. You are right, we did not provide a trained model. That might change in the future. 

As for the data mixing: 
1. We generated the data by randomly placing the microphone array in a room (of also random dimensions). This position (and room dimensions) were changed randomly for each training and testing sample. This also applies to the positions of the source and interferes. 

2. You can use, e.g., https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.room.html, to generate the RIRs. To place the microphone array randomly, simply use python's "random" library. 

Unfortunately, the mixing code requires some cleaning up and commenting which I have not had the chance to do yet. I will try to include it in the future.

**Comment by hido710** [comment]
Thank you for your kind reply.
